version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports: 
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mariadb
    networks:
      - db-network


volumes:
  db-volume:

networks:
  db-network: