#
# AWS EC2 환경변수 주입하는 Ansible Playbook
#

- hosts: ec2_hosts
  become: true
  gather_facts: true

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    instance_map:
      i-04eb2787f4fafb2bb: # fullstack
        KAFKA_BOOTSTRAP_SERVER: "192.166.1.132:19092"
        KAFKA_TOPIC_RELATION: relation
        DB_URL: "jdbc:mariadb://192.166.2.25:3306/fullstackdb"
        DB_USER: "fullstackdb_user"
        DB_PW: "fullstack1234"
        AWS_ACCESS_KEY_ID: AKIA3N7PJZH7R6RPIDWP
        AWS_SECRET_ACCESS_KEY: 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
        AWS_REGION: ap-northeast-2
        AWS_S3_BUCKET_NAME: ktb-bunch-bucket
        RECOMMEND_SERVER_URL: http://192.166.1.141:5000/
      i-02adb488221d704c0: # ai
        DB_HOST: "192.166.2.25"
        MYSQL_DATABASE: "aidb"
        FULLSTACK_DATABASE: "fullstackdb"
        MYSQL_USER: "aidb_user"
        MYSQL_PASSWORD: "ai1234"
        CLIENT_ID: hZm0ny7bv69wAHcdYffq
        CLIENT_SECRET: pIyAPPtzD2
        OLLAMA_BASE_URL: http://192.166.1.141:11434
      i-057eaeb9774d59364: # elk
        BOOTSTRAP_SERVER: "192.166.1.132:19092"
      i-09449a343d5416bf7: # kafka
        BOOTSTRAP_SERVER: "192.166.1.132:19092"
      i-0849326fe5d24f6ad: # db
        MARIADB_ROOT_PASSWORD: "root1234"


  tasks:
    - name: Set fact based on EC2 instance ID
      set_fact:
        instanceID: "{{ ansible_facts['board_asset_tag'] }}"
      tags: always  # 이 태스크는 항상 실행됨
    
    - name: Debug the value of instanceID
      debug:
        var: instanceID 
      tags: always  # 이 태스크는 항상 실행됨

    - name: Add environment variables to /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "{{ item.key }}={{ item.value }}"
        create: yes
      loop: "{{ instance_map[instanceID] | dict2items }}"
      when: instanceID in instance_map.keys()
      tags: add

    - name: Ensure the environment variables are loaded
      ansible.builtin.shell: |
        source /etc/environment
      when: instanceID in instance_map.keys()
      tags: add
    
    - name: Remove /etv/environment 
      ansible.builtin.shell: |
        rm -f /etc/environment
      when: instanceID in instance_map.keys()
      tags: remove