#
# AWS EC2 환경변수 주입하는 Ansible Playbook
#

- hosts: ec2_hosts
  become: true
  gather_facts: true

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    instance_map:
      i-04eb2787f4fafb2bb: # fullstack
        KAFKA_BOOTSTRAP_SERVER: "192.166.1.132:19092"
        KAFKA_TOPIC_RELATION: relation
        DB_URL: "jdbc:mariadb://192.166.2.25:3306/fullstackDB"
        DB_USER: "fullstackDB_user"
        DB_PW: "fullstack1234"

      i-057eaeb9774d59364: # elk
        BOOTSTRAP_SERVER: "192.166.1.132:19092"
      i-09449a343d5416bf7: # kafka
        BOOTSTRAP_SERVER: "192.166.1.132:19092"
      i-0849326fe5d24f6ad: # db
        DB_ROOT_PASSWORD: "root1234"


  tasks:
    - name: Set fact based on EC2 instance ID
      set_fact:
        instanceID: "{{ ansible_facts['board_asset_tag'] }}"
      tags: always  # 이 태스크는 항상 실행됨
    
    - name: Debug the value of instanceID
      debug:
        var: instanceID 
      tags: always  # 이 태스크는 항상 실행됨

    - name: Add environment variables to /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "{{ item.key }}={{ item.value }}"
        create: yes
      loop: "{{ instance_map[instanceID] | dict2items }}"
      when: instanceID in instance_map.keys()
      tags: add

    - name: Ensure the environment variables are loaded
      ansible.builtin.shell: |
        source /etc/environment
      when: instanceID in instance_map.keys()
      tags: add
    
    - name: Remove /etv/environment 
      ansible.builtin.shell: |
        rm -f /etc/environment
      when: instanceID in instance_map.keys()
      tags: remove